In [18]:
import numpy as np
import matplotlib.pyplot as plt

In [75]:
n = 100
apples_width = np.random.normal(6, 1, n)
apples_length = np.random.normal(6, 1, n)
bananas_width = np.random.normal(4, 1, n)
bananas_length = np.random.normal(8, 1, n)
watermelons_width = np.random.normal(20, 1, n)
watermelons_length = np.random.normal(20, 1, n)

In [76]:
width =  np.concatenate ((apples_width, bananas_width, watermelons_width))
length =  np.concatenate ((apples_length, bananas_length, watermelons_length))
x_train = np.array ([width, length]).T
x_train

array([[ 7.22152416,  4.60971369],
       [ 6.1367343 ,  5.84665859],
       [ 4.74578302,  4.80297318],
       [ 6.14663896,  4.91680115],
       [ 5.74328181,  7.07020378],
       [ 6.14642476,  6.01647318],
       [ 6.90660987,  5.87517484],
       [ 7.25781359,  5.26527638],
       [ 8.64062172,  7.02763487],
       [ 5.20880738,  6.70649132],
       [ 5.50860446,  5.08126332],
       [ 5.2903261 ,  7.30481965],
       [ 4.27345949,  5.08035583],
       [ 5.03087712,  7.47556487],
       [ 6.36037861,  4.95456779],
       [ 6.96859858,  5.33067969],
       [ 6.06838153,  5.38456896],
       [ 7.07201987,  6.58011213],
       [ 6.56470566,  4.94665488],
       [ 4.84667752,  6.80640014],
       [ 5.75593227,  7.62158208],
       [ 6.77962512,  5.92487605],
       [ 6.25159967,  6.56415502],
       [ 5.21007395,  5.13305727],
       [ 4.79503564,  6.91706586],
       [ 5.776612  ,  4.99720019],
       [ 6.73379825,  7.65082909],
       [ 5.02660547,  5.48442778],
       [ 6.20304253,

In [77]:
y_apples = np.zeros (n, dtype='int')
y_bananas = np.ones (n, dtype='int')
y_watermelons = np.ones (n, dtype='int')*2
y_train =  np.concatenate ((y_apples, y_bananas, y_watermelons))
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [78]:
def Euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2)**2))

In [80]:
new_fruit = np.array([20, 22])
distances= []
for x in x_train:
         d = Euclidean_distance (new_fruit, x)
         distances.append(d)

distances


[21.58034991744867,
 21.286629008172735,
 22.987580716556515,
 21.994346891148172,
 20.64346939612371,
 21.151706236689805,
 20.77129874639611,
 21.033646596787598,
 18.793807295271655,
 21.27606135498318,
 22.27653912655494,
 20.792374365806346,
 23.099749681592176,
 20.857465229191845,
 21.83085043663214,
 21.158536398282322,
 21.683231816848508,
 20.122266575230178,
 21.70999110501894,
 21.458533479930853,
 20.239376653043898,
 20.813167039135845,
 20.670844731664264,
 22.432914864956764,
 21.416952245912487,
 22.167543111903246,
 19.542026887550836,
 22.29274925784463,
 22.945911279708227,
 21.308832281630018,
 21.22522347346938,
 21.989097472145875,
 21.11316825088467,
 21.381625578131366,
 21.138883844479558,
 20.27818420578304,
 22.948003290317473,
 22.061262415597508,
 21.3656467189043,
 22.303549122728093,
 21.25856598619662,
 22.62156937528009,
 23.12747964614495,
 22.70611725614711,
 20.456443054199045,
 23.451336427913322,
 20.87913888890036,
 20.868587301345144,
 19.287763

In [81]:
k = 5
nearest_neighbors = np.argsort(distances)[0:k]
nearest_neighbors

array([263, 252, 207, 249, 297], dtype=int64)

In [82]:
y_train [nearest_neighbors]

array([2, 2, 2, 2, 2])

In [83]:
result = np.bincount(y_train[nearest_neighbors])

if np.argmax (result) == 0:
    print("🍎🍎🍎")
elif np.argmax (result) == 1:
    print("🍌🍌🍌")
else:
    print("🍉🍉🍉")


🍉🍉🍉
